[package]
name = "aoc2019"
version = "0.1.0"
authors = ["David Hewson <dev@daveid.co.uk>"]
edition = "2018"

[profile.release]
lto = true

[profile.bench]
lto = true

[dependencies]
pathfinding = "2.0.0"
